# Generated by Django 5.2.17 on 2026-08-18 09:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_stock_quantity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('category'), name='unique_product_name_per_category_ci'),
        ),
    ]
