# Generated by Django 5.2.17 on 2026-08-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_unique_product_name_per_category_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, default=''),
        ),
    ]
