# Generated by Django 5.2.17 on 2026-08-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_checkoutsession_cod_amount_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsession',
            name='cod_amount_due',
        ),
        migrations.RemoveField(
            model_name='checkoutsession',
            name='order_total',
        ),
        migrations.RemoveField(
            model_name='checkoutsession',
            name='payment_method',
        ),
    ]
