# Generated by Django 5.2.17 on 2026-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_checkoutsession_cod_amount_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_proof',
            field=models.ImageField(blank=True, null=True, upload_to='orders/delivery_proof/'),
        ),
    ]
