# Generated by Django 5.2.17 on 2026-08-10 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_blogpost_portfolioitem_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('general', 'General'), ('product', 'Product'), ('build_tank', 'Build Tank')], default='general', max_length=20)),
                ('tank_size', models.CharField(blank=True, max_length=100)),
                ('tank_shape', models.CharField(blank=True, max_length=100)),
                ('budget_notes', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='inquiries_i_status_8fae14_idx'), models.Index(fields=['type'], name='inquiries_i_type_ed589c_idx')],
            },
        ),
    ]
